import * as stylex from '@stylexjs/stylex'

export const colors = stylex.defineVars({
  background: '#060608',
  ink: '#edecea',
  soft: '#b9b8bd',
  muted: '#83838c',
  faint: '#4c4c55',
  line: 'rgba(237, 236, 234, 0.14)',
})

const sans = "'Geist Variable', ui-sans-serif, system-ui, sans-serif"
const mono = "'Geist Mono Variable', ui-monospace, 'SF Mono', Menlo, monospace"

export const styles = stylex.create({
  html: {
    height: '100%',
    colorScheme: 'dark',
  },
  body: {
    margin: 0,
    padding: 0,
    height: '100%',
    minHeight: '100dvh',
    overflow: 'hidden',
    backgroundColor: colors.background,
    color: colors.ink,
    fontFamily: sans,
    WebkitFontSmoothing: 'antialiased',
    textRendering: 'optimizeLegibility',
  },
  canvas: {
    position: 'fixed',
    inset: 0,
    zIndex: 0,
    display: 'block',
    width: '100%',
    height: '100%',
    opacity: 0,
    cursor: 'grab',
    touchAction: 'none',
    transitionProperty: 'opacity',
    transitionDuration: '1.8s',
    transitionTimingFunction: 'cubic-bezier(0.2, 0.65, 0.2, 1)',
  },
  fixedAtmosphere: {
    position: 'fixed',
    inset: 0,
    zIndex: 1,
    pointerEvents: 'none',
  },
  aurora: {
    backgroundImage: {
      default: 'radial-gradient(ellipse 52% 58% at 72% 42%, rgba(63, 94, 112, 0.12), transparent 72%), linear-gradient(90deg, rgba(6, 6, 8, 0.54) 0%, transparent 52%)',
      '@media (max-width: 700px)': 'radial-gradient(ellipse 82% 40% at 50% 29%, rgba(63, 94, 112, 0.12), transparent 75%), linear-gradient(0deg, rgba(6, 6, 8, 0.58) 0%, transparent 58%)',
    },
  },
  vignette: {
    backgroundImage: 'radial-gradient(130% 110% at 62% 30%, transparent 48%, rgba(0, 0, 0, 0.55) 100%)',
  },
  grain: {
    inset: '-50%',
    opacity: 0.035,
    backgroundImage: 'url("data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'140\' height=\'140\'%3E%3Cfilter id=\'n\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.85\' numOctaves=\'2\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'140\' height=\'140\' filter=\'url(%23n)\'/%3E%3C/svg%3E")',
  },
  main: {
    position: 'relative',
    zIndex: 2,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    minHeight: '100dvh',
    padding: 'clamp(1.4rem, 3.5vw, 3.25rem)',
    paddingTop: 'max(clamp(1.4rem, 3.5vw, 3.25rem), env(safe-area-inset-top))',
    paddingBottom: 'max(clamp(1.4rem, 3.5vw, 3.25rem), env(safe-area-inset-bottom))',
    pointerEvents: 'none',
  },
  topbar: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    fontFamily: mono,
    fontSize: '0.72rem',
    letterSpacing: '0.16em',
    textTransform: 'uppercase',
  },
  mark: {
    color: colors.ink,
  },
  place: {
    display: {
      default: 'inline',
      '@media (max-width: 460px)': 'none',
    },
    color: colors.faint,
  },
  sceneMeta: {
    position: 'absolute',
    top: '50%',
    right: 'max(clamp(1.4rem, 3.5vw, 3.25rem), env(safe-area-inset-right))',
    display: {
      default: 'flex',
      '@media (max-width: 700px)': 'none',
    },
    flexDirection: 'column',
    gap: '0.45rem',
    color: 'rgba(185, 184, 189, 0.34)',
    fontFamily: mono,
    fontSize: '0.58rem',
    letterSpacing: '0.18em',
    textAlign: 'right',
    transform: 'translateY(-50%)',
  },
  sceneCredit: {
    color: 'rgba(131, 131, 140, 0.44)',
  },
  bottom: {
    display: 'flex',
    flexDirection: 'column',
    gap: 'clamp(2rem, 5vh, 3.5rem)',
  },
  intro: {
    maxWidth: '40rem',
  },
  kicker: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: '1.1rem',
    marginLeft: 0,
    color: colors.muted,
    fontFamily: mono,
    fontSize: 'clamp(0.72rem, 1.6vw, 0.82rem)',
    letterSpacing: '0.22em',
    textTransform: 'uppercase',
  },
  heading: {
    margin: 0,
    color: '#f6f5f3',
    fontFamily: sans,
    fontSize: 'clamp(2.7rem, 9vw, 5rem)',
    fontWeight: 600,
    lineHeight: 0.95,
    letterSpacing: '-0.035em',
  },
  lede: {
    maxWidth: '40ch',
    marginTop: '1.5rem',
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: colors.soft,
    fontSize: 'clamp(1rem, 2.3vw, 1.2rem)',
    fontWeight: 350,
    lineHeight: 1.62,
  },
  links: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '1.6rem',
    marginTop: '2.4rem',
    fontFamily: mono,
    fontSize: '0.8rem',
    letterSpacing: '0.04em',
  },
  link: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.5em',
    paddingBottom: '0.35em',
    borderBottomStyle: 'solid',
    borderBottomWidth: '1px',
    borderBottomColor: {
      default: 'transparent',
      ':hover': colors.line,
      ':focus-visible': colors.line,
    },
    color: {
      default: colors.soft,
      ':hover': colors.ink,
      ':focus-visible': colors.ink,
    },
    textDecoration: 'none',
    outline: 'none',
    pointerEvents: 'auto',
    transitionProperty: 'color, border-color',
    transitionDuration: '0.3s',
    transitionTimingFunction: 'ease',
  },
  linkIcon: {
    color: colors.faint,
    transitionProperty: 'transform, color',
    transitionDuration: '0.3s',
    transitionTimingFunction: 'ease',
  },
  footer: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.7em',
    color: colors.faint,
    fontFamily: mono,
    fontSize: '0.7rem',
    letterSpacing: '0.16em',
    textTransform: 'uppercase',
  },
  footerLink: {
    borderBottomStyle: 'solid',
    borderBottomWidth: '1px',
    borderBottomColor: {
      default: 'transparent',
      ':hover': colors.line,
      ':focus-visible': colors.line,
    },
    color: {
      default: colors.muted,
      ':hover': colors.ink,
      ':focus-visible': colors.ink,
    },
    textDecoration: 'none',
    outline: 'none',
    pointerEvents: 'auto',
    transitionProperty: 'color, border-color',
    transitionDuration: '0.3s',
    transitionTimingFunction: 'ease',
  },
  separator: {
    color: colors.faint,
  },
  motionControl: {
    position: 'absolute',
    right: 'max(clamp(1.4rem, 3.5vw, 3.25rem), env(safe-area-inset-right))',
    bottom: 'max(clamp(1.4rem, 3.5vw, 3.25rem), env(safe-area-inset-bottom))',
    display: {
      default: 'inline-flex',
      '@media (max-width: 700px)': 'none',
      '@media (prefers-reduced-motion: reduce)': 'none',
    },
    alignItems: 'center',
    gap: '0.65rem',
    padding: 0,
    borderWidth: 0,
    backgroundColor: 'transparent',
    color: {
      default: colors.muted,
      ':hover': colors.ink,
      ':focus-visible': colors.ink,
    },
    fontFamily: mono,
    fontSize: '0.65rem',
    letterSpacing: '0.13em',
    textTransform: 'uppercase',
    cursor: 'pointer',
    pointerEvents: 'auto',
    outline: 'none',
  },
  motionIcon: {
    position: 'relative',
    width: '1.35rem',
    height: '1.35rem',
    borderStyle: 'solid',
    borderWidth: '1px',
    borderColor: 'rgba(185, 184, 189, 0.3)',
    borderRadius: '50%',
  },
})
